name: build linux kernel
on:
 workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: upload 
              uses: svenstaro/upload-release-action@v2
              with:
                   repo_token: ${{ secrets.GITHUB_TOKEN }}
                   tag: ${{ github.ref }}
                   file: README.md
                   overwrite: true
