name: build linux kernel
on:
    push:
        tags:
            - 'v*'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                  sparse-checkout: |
                      PKGBUILD
                  sparse-checkout-cone-mode: false
            - name: build and check
              id: makepkg
              uses: edlanglois/pkgbuild-action@v1
              with:
                  pkgdir: ../
            - name: Print Package Files
              run: |
                  echo "Successfully created the following package archive"
                  echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
            - name: upload to release
              uses: softprops/action-gh-release@v2
              with:
                  files: build/*
                  fail_on_unmatched_files: true
