name: build linux kernel
on:
 workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout pkgbuild file
              id: checkout
              uses: actions/checkout@v4
              with:
                  sparse-checkout: |
                      PKGBUILD
                  sparse-checkout-cone-mode: false
            - name: build and check
              id: makepkg
              uses: edlanglois/pkgbuild-action@v1
            - name: Print Package Files
              run: |
                  echo "Successfully created the following package archive"
                  echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
            - name: upload to release
              id: upload
              uses: softprops/action-gh-release@v2
              with:
                  files: build/*
                  fail_on_unmatched_files: true
